/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description `values` is not_started, warming, ready, or failed.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Plans */
        post: operations["compare_plans_api_plans_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/counterfactual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Counterfactual */
        post: operations["run_counterfactual_api_plans_counterfactual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddCrewDay */
        AddCrewDay: {
            /** Allowed Clusters */
            allowed_clusters: string[];
            /**
             * Available Min
             * @description Integer minutes
             */
            available_min: number;
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "add_crew_day";
            /** Skills */
            skills: string[];
        };
        /**
         * Algorithm
         * @enum {string}
         */
        Algorithm: "cpsat" | "baseline_edf" | "baseline_nearest_cluster";
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /**
             * Input Issues
             * @default []
             */
            input_issues: components["schemas"]["InputIssue"][];
            /** Message */
            message: string;
        };
        /** Assignment */
        Assignment: {
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Days Late
             * @description Whole days
             * @default 0
             */
            days_late: number;
            /** Site Id */
            site_id: string;
            state: components["schemas"]["JobState"];
            /**
             * Value Usd
             * @description Value, USD
             * @default 0
             */
            value_usd: number;
        };
        /** Assumption */
        Assumption: {
            /** Key */
            key: string;
            kind: components["schemas"]["DataKind"];
            /** Text */
            text: string;
        };
        /** BatteryConfig */
        BatteryConfig: {
            /**
             * Capacity Kwh
             * @description Energy, kWh
             */
            capacity_kwh: number;
            /**
             * Charge Limit Kw
             * @description Power, kW
             */
            charge_limit_kw: number;
            /** Configuration Id */
            configuration_id: string;
            /**
             * Discharge Limit Kw
             * @description Power, kW
             */
            discharge_limit_kw: number;
            /** Eta Charge */
            eta_charge: number;
            /** Eta Discharge */
            eta_discharge: number;
            /**
             * Reserve Kwh
             * @description Energy, kWh
             */
            reserve_kwh: number;
        };
        /**
         * ChangeKind
         * @enum {string}
         */
        ChangeKind: "added" | "removed" | "moved" | "state_changed";
        /** ChangeReadyDate */
        ChangeReadyDate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "change_ready_date";
            /**
             * Ready Date
             * Format: date
             */
            ready_date: string;
            /** Site Id */
            site_id: string;
        };
        /** Cluster */
        Cluster: {
            /** Cluster Id */
            cluster_id: string;
            /** Name */
            name: string;
            /**
             * Outline
             * @description Closed ring of (lon, lat)
             */
            outline: [
                number,
                number
            ][];
            /**
             * Travel Allowance Min
             * @description Integer minutes
             */
            travel_allowance_min: number;
        };
        /** CompareRequest */
        CompareRequest: {
            after: components["schemas"]["PlanResult"];
            before: components["schemas"]["PlanResult"];
        };
        /** CounterfactualRequest */
        CounterfactualRequest: {
            base: components["schemas"]["PlanResult"];
            /** Intervention */
            intervention: components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"];
            /** @description The request that produced base */
            request: components["schemas"]["PlanRequest"];
        };
        /** CounterfactualResult */
        CounterfactualResult: {
            diff: components["schemas"]["PlanDiff"];
            /** Feasible */
            feasible: boolean;
            /** Intervention */
            intervention: components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"];
            result: components["schemas"]["PlanResult"];
            /** Summary */
            summary: string;
        };
        /** CrewDay */
        CrewDay: {
            /** Allowed Clusters */
            allowed_clusters: string[];
            /**
             * Available Min
             * @description Integer minutes
             */
            available_min: number;
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Skills */
            skills: string[];
        };
        /** CrewDayUsage */
        CrewDayUsage: {
            /**
             * Available Min
             * @description Integer minutes
             */
            available_min: number;
            /** Cluster Id */
            cluster_id: string | null;
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Onsite Min
             * @description Integer minutes
             */
            onsite_min: number;
            /**
             * Travel Min
             * @description Integer minutes
             */
            travel_min: number;
        };
        /**
         * DataKind
         * @enum {string}
         */
        DataKind: "observed" | "modeled" | "derived" | "assumed" | "synthetic";
        /** DelayInventory */
        DelayInventory: {
            /** Configuration Id */
            configuration_id: string;
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "delay_inventory";
            /**
             * Quantity
             * @description None moves the whole receipt
             */
            quantity?: number | null;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
        };
        /** DiffSummary */
        DiffSummary: {
            /** Added */
            added: number;
            /** Moved */
            moved: number;
            /** Newly Late */
            newly_late: number;
            /** Removed */
            removed: number;
            /** Travel Delta Min */
            travel_delta_min: number;
            /**
             * Value Delta Usd
             * @description Value, USD
             */
            value_delta_usd: number;
        };
        /** ForceInclude */
        ForceInclude: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "force_include";
            /** Site Id */
            site_id: string;
        };
        /** InputIssue */
        InputIssue: {
            code: components["schemas"]["InputIssueCode"];
            /** File */
            file?: string | null;
            /** Message */
            message: string;
            /** Row */
            row?: number | null;
        };
        /**
         * InputIssueCode
         * @enum {string}
         */
        InputIssueCode: "DUPLICATE_ID" | "UNKNOWN_REFERENCE" | "BAD_VALUE" | "DATE_ORDER" | "DUPLICATE_PLANNED_INSTALL" | "CONTRADICTORY_LOCKS" | "MISSING_INTERVAL" | "MISSING_FILE";
        /** InventoryReceipt */
        InventoryReceipt: {
            /**
             * Available Date
             * Format: date
             */
            available_date: string;
            /** Configuration Id */
            configuration_id: string;
            /**
             * Quantity
             * @description Incoming units on this date, not a balance
             */
            quantity: number;
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "scheduled" | "locked" | "late" | "unscheduled" | "blocked";
        /**
         * Mode
         * @enum {string}
         */
        Mode: "strict" | "recovery";
        /** ObjectiveComponents */
        ObjectiveComponents: {
            /** Changed Installs */
            changed_installs: number;
            /** Crew Utilization */
            crew_utilization: number;
            /** Jobs Blocked */
            jobs_blocked: number;
            /** Jobs Late */
            jobs_late: number;
            /** Jobs On Time */
            jobs_on_time: number;
            /**
             * Jobs Unscheduled
             * @description Includes blocked jobs
             */
            jobs_unscheduled: number;
            /**
             * Operating Value Usd
             * @description Value, USD
             */
            operating_value_usd: number;
            /**
             * Total Delay Days
             * @description Sum of days late over assigned jobs
             */
            total_delay_days: number;
            /**
             * Travel Allowance Min
             * @description Integer minutes
             */
            travel_allowance_min: number;
            /** Value Distinguishes Choices */
            value_distinguishes_choices: boolean;
        };
        /**
         * ObjectivePolicy
         * @enum {string}
         */
        ObjectivePolicy: "value_aware" | "deadline_travel_only";
        /**
         * Parameter
         * @description One operational number the model uses, with where it came from.
         */
        Parameter: {
            /**
             * Derivation
             * @description Rule, formula, or citation that produced the value
             */
            derivation: string;
            kind: components["schemas"]["DataKind"];
            /** Name */
            name: string;
            /**
             * Source
             * @description URL or reference, when one exists
             */
            source?: string | null;
            /** Unit */
            unit: string;
            /** Value */
            value: number | string;
        };
        /** PlanChange */
        PlanChange: {
            after: components["schemas"]["Slot"] | null;
            after_state: components["schemas"]["JobState"];
            before: components["schemas"]["Slot"] | null;
            before_state: components["schemas"]["JobState"];
            kind: components["schemas"]["ChangeKind"];
            /** Note */
            note: string;
            /** Site Id */
            site_id: string;
        };
        /** PlanDiff */
        PlanDiff: {
            /** After Plan Id */
            after_plan_id: string;
            /** Before Plan Id */
            before_plan_id: string;
            /** Changes */
            changes: components["schemas"]["PlanChange"][];
            /** Headline */
            headline: string;
            summary: components["schemas"]["DiffSummary"];
        };
        /** PlanRequest */
        PlanRequest: {
            /** @default cpsat */
            algorithm: components["schemas"]["Algorithm"];
            /**
             * Edits
             * @default []
             */
            edits: (components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"])[];
            /** @default strict */
            mode: components["schemas"]["Mode"];
            objective_policy?: components["schemas"]["ObjectivePolicy"] | null;
            /**
             * Revision
             * @description Client edit counter, echoed in the result
             */
            revision: number;
            /** Scenario Id */
            scenario_id: string;
            /** Time Limit S */
            time_limit_s?: number | null;
        };
        /** PlanResult */
        PlanResult: {
            algorithm: components["schemas"]["Algorithm"];
            /** Assignments */
            assignments: components["schemas"]["Assignment"][];
            /** Assumptions */
            assumptions: components["schemas"]["Assumption"][];
            /** Crew Days */
            crew_days: components["schemas"]["CrewDayUsage"][];
            /** Edits */
            edits: (components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"])[];
            /**
             * Input Issues
             * @default []
             */
            input_issues: components["schemas"]["InputIssue"][];
            /**
             * Message
             * @description One or two plain sentences for the operator
             */
            message: string;
            mode: components["schemas"]["Mode"];
            objective: components["schemas"]["ObjectiveComponents"] | null;
            objective_policy: components["schemas"]["ObjectivePolicy"];
            /** Plan Id */
            plan_id: string;
            /** Revision */
            revision: number;
            /** Scenario Hash */
            scenario_hash: string;
            /** Scenario Id */
            scenario_id: string;
            /** Solve Ms */
            solve_ms: number;
            /** Stages */
            stages: components["schemas"]["StageMeta"][];
            status: components["schemas"]["PlanStatus"];
            /** Unscheduled */
            unscheduled: components["schemas"]["UnscheduledJob"][];
            validation: components["schemas"]["ValidationReport"];
        };
        /**
         * PlanStatus
         * @enum {string}
         */
        PlanStatus: "optimal" | "feasible" | "infeasible" | "timeout_no_incumbent" | "invalid_input";
        /**
         * PlannedInstall
         * @description One row of the current installation plan that a disruption may force to change.
         */
        PlannedInstall: {
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Locked */
            locked: boolean;
            /** Site Id */
            site_id: string;
        };
        /** ProvenanceNote */
        ProvenanceNote: {
            /**
             * Input
             * @description File or field this note covers, e.g. sites.csv:deadline
             */
            input: string;
            kind: components["schemas"]["DataKind"];
            /** Manifest Id */
            manifest_id?: string | null;
            /** Source */
            source: string;
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "NOT_READY" | "SKILL_MISMATCH" | "CLUSTER_NOT_ALLOWED" | "NO_LEGAL_DATE" | "NO_INVENTORY" | "CAPACITY" | "LOCK_CONFLICT" | "DEADLINE_BEFORE_READY";
        /** RemoveCrewDay */
        RemoveCrewDay: {
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "remove_crew_day";
        };
        /** Scenario */
        Scenario: {
            /** Clusters */
            clusters: components["schemas"]["Cluster"][];
            config: components["schemas"]["ScenarioConfig"];
            /** Crew Days */
            crew_days: components["schemas"]["CrewDay"][];
            /** Current Plan */
            current_plan: components["schemas"]["PlannedInstall"][];
            /** Inventory */
            inventory: components["schemas"]["InventoryReceipt"][];
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Scenario Hash */
            scenario_hash: string;
            /** Scenario Id */
            scenario_id: string;
            /** Sites */
            sites: components["schemas"]["Site"][];
        };
        /** ScenarioConfig */
        ScenarioConfig: {
            /** Batteries */
            batteries: components["schemas"]["BatteryConfig"][];
            /** Description */
            description: string;
            /**
             * Evaluation End
             * Format: date
             */
            evaluation_end: string;
            /** Name */
            name: string;
            /**
             * Num Workers
             * @default 8
             */
            num_workers: number;
            /** @default value_aware */
            objective_policy: components["schemas"]["ObjectivePolicy"];
            /**
             * Parameters
             * @default []
             */
            parameters: components["schemas"]["Parameter"][];
            /**
             * Planning End
             * Format: date
             */
            planning_end: string;
            /**
             * Planning Start
             * Format: date
             */
            planning_start: string;
            /** Provenance */
            provenance: components["schemas"]["ProvenanceNote"][];
            /**
             * Qualification Lag Days
             * @description Whole days
             * @default 0
             */
            qualification_lag_days: number;
            /**
             * Random Seed
             * @default 0
             */
            random_seed: number;
            /**
             * Solve Time Limit S
             * @default 15
             */
            solve_time_limit_s: number;
            /** Synthetic */
            synthetic: boolean;
            /**
             * Timezone
             * @default America/Chicago
             */
            timezone: string;
            /**
             * Unscheduled Penalty Days
             * @description Whole days
             */
            unscheduled_penalty_days: number;
            weather_rule?: components["schemas"]["WeatherRule"] | null;
        };
        /** ScenarioSummary */
        ScenarioSummary: {
            /** N Crew Days */
            n_crew_days: number;
            /** N Crews */
            n_crews: number;
            /** N Sites */
            n_sites: number;
            /** Name */
            name: string;
            /**
             * Planning End
             * Format: date
             */
            planning_end: string;
            /**
             * Planning Start
             * Format: date
             */
            planning_start: string;
            /** Scenario Hash */
            scenario_hash: string;
            /** Scenario Id */
            scenario_id: string;
            /** Synthetic */
            synthetic: boolean;
        };
        /** Site */
        Site: {
            /** Cluster Id */
            cluster_id: string;
            /** Configuration Id */
            configuration_id: string;
            /**
             * Deadline
             * Format: date
             */
            deadline: string;
            /**
             * Duration Min
             * @description Integer minutes
             */
            duration_min: number;
            /** Lat */
            lat: number;
            /** Load Zone */
            load_zone: string;
            /** Lon */
            lon: number;
            /** Profile Id */
            profile_id?: string | null;
            /** Program Id */
            program_id: string;
            /**
             * Ready Date
             * Format: date
             */
            ready_date: string;
            /** Required Skill */
            required_skill: string;
            /** Site Id */
            site_id: string;
        };
        /** Slot */
        Slot: {
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** StageMeta */
        StageMeta: {
            /** Bound */
            bound?: number | null;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Gap */
            gap?: number | null;
            /** Name */
            name: string;
            status: components["schemas"]["StageStatus"];
            /** Value */
            value?: number | null;
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "optimal" | "feasible" | "infeasible" | "timeout_no_incumbent" | "skipped";
        /** UnscheduledJob */
        UnscheduledJob: {
            /** Detail */
            detail: string;
            /** Reasons */
            reasons: components["schemas"]["ReasonCode"][];
            /** Site Id */
            site_id: string;
            state: components["schemas"]["JobState"];
        };
        /** ValidationIssue */
        ValidationIssue: {
            code: components["schemas"]["ViolationCode"];
            /** Crew Id */
            crew_id?: string | null;
            /** Date */
            date?: string | null;
            /** Message */
            message: string;
            /** Site Id */
            site_id?: string | null;
        };
        /** ValidationReport */
        ValidationReport: {
            /**
             * Checked
             * @description False until the independent validator ran
             */
            checked: boolean;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["ValidationIssue"][];
            /** Valid */
            valid: boolean;
            /** Validator */
            validator: string;
        };
        /**
         * ViolationCode
         * @enum {string}
         */
        ViolationCode: "UNKNOWN_SITE" | "DUPLICATE_ASSIGNMENT" | "NO_CREW_DAY" | "BEFORE_READY" | "AFTER_DEADLINE" | "MISSING_JOB" | "SKILL" | "CLUSTER_NOT_ALLOWED" | "MULTIPLE_CLUSTERS" | "CAPACITY" | "INVENTORY" | "LOCK_BROKEN" | "STATE_MISMATCH" | "OBJECTIVE_MISMATCH";
        /**
         * WeatherRule
         * @description A crew-day is lost when any working hour meets either condition.
         */
        WeatherRule: {
            /** Heavy Rain Mm Per H */
            heavy_rain_mm_per_h: number;
            /**
             * Thunder
             * @description Lose the day on any reported thunderstorm
             * @default true
             */
            thunder: boolean;
            /**
             * Work End Hour
             * @description Exclusive
             */
            work_end_hour: number;
            /** Work Start Hour */
            work_start_hour: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_plan_api_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
            /** @description The request is valid JSON but makes no sense */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown scenario or path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request or the scenario files are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The planner produced a plan that failed validation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    compare_plans_api_plans_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDiff"];
                };
            };
            /** @description The request is valid JSON but makes no sense */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown scenario or path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request or the scenario files are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The planner produced a plan that failed validation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    run_counterfactual_api_plans_counterfactual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CounterfactualRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterfactualResult"];
                };
            };
            /** @description The request is valid JSON but makes no sense */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown scenario or path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request or the scenario files are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The planner produced a plan that failed validation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
    get_scenario_api_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"];
                };
            };
            /** @description The request is valid JSON but makes no sense */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown scenario or path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request or the scenario files are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The planner produced a plan that failed validation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
