/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_api_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description `values` is not_started, warming, ready, or failed.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare Plans */
        post: operations["compare_plans_api_plans_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/counterfactual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Counterfactual */
        post: operations["run_counterfactual_api_plans_counterfactual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recovery/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recovery Approve */
        post: operations["recovery_approve_api_recovery_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recovery/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recovery Evaluate */
        post: operations["recovery_evaluate_api_recovery_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recovery/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recovery Options */
        post: operations["recovery_options_api_recovery_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/season-replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season Replay */
        get: operations["season_replay_api_season_replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Storms */
        get: operations["list_storms_api_storms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddCrewDay */
        AddCrewDay: {
            /** Allowed Clusters */
            allowed_clusters: string[];
            /**
             * Available Min
             * @description Integer minutes
             */
            available_min: number;
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "add_crew_day";
            /** Skills */
            skills: string[];
        };
        /**
         * Algorithm
         * @enum {string}
         */
        Algorithm: "cpsat" | "baseline_edf" | "baseline_nearest_cluster";
        /** ApiError */
        ApiError: {
            /** Code */
            code: string;
            /**
             * Input Issues
             * @default []
             */
            input_issues: components["schemas"]["InputIssue"][];
            /** Message */
            message: string;
        };
        /** ApproveRequest */
        ApproveRequest: {
            option: components["schemas"]["RecoveryOption"];
            /** Revision */
            revision: number;
            /** Scenario Id */
            scenario_id: string;
        };
        /** ApproveResult */
        ApproveResult: {
            effective_scenario?: components["schemas"]["Scenario"] | null;
            /** New Current Plan */
            new_current_plan: components["schemas"]["PlannedInstall"][];
            /**
             * Stub
             * @default false
             */
            stub: boolean;
            /** Summary */
            summary: string;
        };
        /** Assignment */
        Assignment: {
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Days Late
             * @description Whole days
             * @default 0
             */
            days_late: number;
            /**
             * Job Id
             * @description Visit job; None for one-visit homes
             */
            job_id?: string | null;
            /** Site Id */
            site_id: string;
            state: components["schemas"]["JobState"];
            /**
             * Value Usd
             * @description Value, USD
             * @default 0
             */
            value_usd: number;
            visit_type?: components["schemas"]["VisitType"] | null;
        };
        /** Assumption */
        Assumption: {
            /** Key */
            key: string;
            kind: components["schemas"]["DataKind"];
            /** Text */
            text: string;
        };
        /** BatteryConfig */
        BatteryConfig: {
            /**
             * Capacity Kwh
             * @description Energy, kWh
             */
            capacity_kwh: number;
            /**
             * Charge Limit Kw
             * @description Power, kW
             */
            charge_limit_kw: number;
            /** Configuration Id */
            configuration_id: string;
            /**
             * Discharge Limit Kw
             * @description Power, kW
             */
            discharge_limit_kw: number;
            /** Eta Charge */
            eta_charge: number;
            /** Eta Discharge */
            eta_discharge: number;
            /**
             * Reserve Kwh
             * @description Energy, kWh
             */
            reserve_kwh: number;
        };
        /**
         * CascadeKind
         * @enum {string}
         */
        CascadeKind: "disruption" | "direct" | "pushed" | "commitment";
        /**
         * CascadeStep
         * @description disruption -> directly affected visits -> battery days pushed -> commitments missed.
         */
        CascadeStep: {
            /** Job Ids */
            job_ids: string[];
            kind: components["schemas"]["CascadeKind"];
            /** Label */
            label: string;
        };
        /** Case */
        Case: {
            /** Case Id */
            case_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Disruption */
            disruption: (components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"] | components["schemas"]["ReduceCrewDay"] | components["schemas"]["ChangeAppointment"] | components["schemas"]["ExtendCrewDay"] | components["schemas"]["PinVisit"] | components["schemas"]["MoveVisit"])[];
            /**
             * Modeled Rule
             * @description The modeled weather-to-disruption rule applied
             */
            modeled_rule: string;
            /** Name */
            name: string;
            /** Provenance */
            provenance: components["schemas"]["ProvenanceNote"][];
            /** Storm Event Id */
            storm_event_id?: string | null;
            /**
             * Stub
             * @default false
             */
            stub: boolean;
            /** Summary */
            summary: string;
        };
        /**
         * ChangeAppointment
         * @description Disruption: the customer can only host this visit inside the new window.
         */
        ChangeAppointment: {
            /**
             * Available From
             * Format: date
             */
            available_from: string;
            /** Available To */
            available_to?: string | null;
            /** Job Id */
            job_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "change_appointment";
        };
        /**
         * ChangeKind
         * @enum {string}
         */
        ChangeKind: "added" | "removed" | "moved" | "state_changed";
        /** ChangeReadyDate */
        ChangeReadyDate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "change_ready_date";
            /**
             * Ready Date
             * Format: date
             */
            ready_date: string;
            /** Site Id */
            site_id: string;
        };
        /** Cluster */
        Cluster: {
            /** Cluster Id */
            cluster_id: string;
            /** Name */
            name: string;
            /**
             * Outline
             * @description Closed ring of (lon, lat)
             */
            outline: [
                number,
                number
            ][];
            /**
             * Travel Allowance Min
             * @description Integer minutes
             */
            travel_allowance_min: number;
        };
        /** CompareRequest */
        CompareRequest: {
            after: components["schemas"]["PlanResult"];
            before: components["schemas"]["PlanResult"];
        };
        /** CounterfactualRequest */
        CounterfactualRequest: {
            base: components["schemas"]["PlanResult"];
            /** Intervention */
            intervention: components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"] | components["schemas"]["ReduceCrewDay"] | components["schemas"]["ChangeAppointment"] | components["schemas"]["ExtendCrewDay"] | components["schemas"]["PinVisit"] | components["schemas"]["MoveVisit"];
            /** @description The request that produced base */
            request: components["schemas"]["PlanRequest"];
        };
        /** CounterfactualResult */
        CounterfactualResult: {
            diff: components["schemas"]["PlanDiff"];
            /** Feasible */
            feasible: boolean;
            /** Intervention */
            intervention: components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"] | components["schemas"]["ReduceCrewDay"] | components["schemas"]["ChangeAppointment"] | components["schemas"]["ExtendCrewDay"] | components["schemas"]["PinVisit"] | components["schemas"]["MoveVisit"];
            result: components["schemas"]["PlanResult"];
            /** Summary */
            summary: string;
        };
        /** CrewDay */
        CrewDay: {
            /** Allowed Clusters */
            allowed_clusters: string[];
            /**
             * Available Min
             * @description Integer minutes
             */
            available_min: number;
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Skills */
            skills: string[];
        };
        /** CrewDayUsage */
        CrewDayUsage: {
            /**
             * Available Min
             * @description Integer minutes
             */
            available_min: number;
            /** Cluster Id */
            cluster_id: string | null;
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Onsite Min
             * @description Integer minutes
             */
            onsite_min: number;
            /**
             * Travel Min
             * @description Integer minutes
             */
            travel_min: number;
        };
        /** CrewLoad */
        CrewLoad: {
            /** After */
            after: number;
            /** Before */
            before: number;
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /**
         * DataKind
         * @enum {string}
         */
        DataKind: "observed" | "modeled" | "derived" | "assumed" | "synthetic";
        /** DelayInventory */
        DelayInventory: {
            /** Configuration Id */
            configuration_id: string;
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "delay_inventory";
            /**
             * Quantity
             * @description None moves the whole receipt
             */
            quantity?: number | null;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
        };
        /** DiffSummary */
        DiffSummary: {
            /** Added */
            added: number;
            /** Customers To Reschedule */
            customers_to_reschedule?: number | null;
            /** Moved */
            moved: number;
            /** Newly Late */
            newly_late: number;
            /** Removed */
            removed: number;
            /** Travel Delta Min */
            travel_delta_min: number;
            /**
             * Value Delta Usd
             * @description Value, USD
             */
            value_delta_usd: number;
        };
        /** EconomicAssumption */
        EconomicAssumption: {
            /** Editable */
            editable: boolean;
            /** Key */
            key: string;
            kind: components["schemas"]["DataKind"];
            /** Source */
            source: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /**
         * EconomicKind
         * @enum {string}
         */
        EconomicKind: "labor" | "value" | "penalty" | "other";
        /** EconomicLine */
        EconomicLine: {
            /**
             * Amount Usd
             * @description Positive is a cost, negative is a saving
             */
            amount_usd: number;
            /**
             * Basis
             * @description How the amount was computed, with its sources
             */
            basis: string;
            kind: components["schemas"]["EconomicKind"];
            /** Label */
            label: string;
        };
        /**
         * EvaluateRequest
         * @description Any manual change (knock out, stretch, drag, pin). Returns an option of kind custom.
         */
        EvaluateRequest: {
            /** Current Plan */
            current_plan?: components["schemas"]["PlannedInstall"][] | null;
            /** Disruption */
            disruption: (components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"] | components["schemas"]["ReduceCrewDay"] | components["schemas"]["ChangeAppointment"] | components["schemas"]["ExtendCrewDay"] | components["schemas"]["PinVisit"] | components["schemas"]["MoveVisit"])[];
            /** Economics Overrides */
            economics_overrides?: {
                [key: string]: number;
            } | null;
            /**
             * Interactive
             * @default true
             */
            interactive: boolean;
            /** Interventions */
            interventions: (components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"] | components["schemas"]["ReduceCrewDay"] | components["schemas"]["ChangeAppointment"] | components["schemas"]["ExtendCrewDay"] | components["schemas"]["PinVisit"] | components["schemas"]["MoveVisit"])[];
            /** Revision */
            revision: number;
            /** Scenario Id */
            scenario_id: string;
        };
        /** Explanation */
        Explanation: {
            /** Constraint */
            constraint: string;
            /** Job Id */
            job_id: string;
            /** Text */
            text: string;
        };
        /**
         * ExtendCrewDay
         * @description Intervention: overtime. The crew-day gets extra minutes.
         */
        ExtendCrewDay: {
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Extra Min
             * @description Integer minutes
             */
            extra_min: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "extend_crew_day";
        };
        /** ForceInclude */
        ForceInclude: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "force_include";
            /** Site Id */
            site_id: string;
        };
        /** ImpactAnalysis */
        ImpactAnalysis: {
            /** Affected Job Ids */
            affected_job_ids: string[];
            /** Cascade */
            cascade: components["schemas"]["CascadeStep"][];
            /** Deadlines At Risk */
            deadlines_at_risk: number;
            /** Headline */
            headline: string;
            /**
             * Lost Capacity Min
             * @description Integer minutes
             */
            lost_capacity_min: number;
        };
        /** InputIssue */
        InputIssue: {
            code: components["schemas"]["InputIssueCode"];
            /** File */
            file?: string | null;
            /** Message */
            message: string;
            /** Row */
            row?: number | null;
        };
        /**
         * InputIssueCode
         * @enum {string}
         */
        InputIssueCode: "DUPLICATE_ID" | "UNKNOWN_REFERENCE" | "BAD_VALUE" | "DATE_ORDER" | "DUPLICATE_PLANNED_INSTALL" | "CONTRADICTORY_LOCKS" | "MISSING_INTERVAL" | "MISSING_FILE";
        /** InventoryReceipt */
        InventoryReceipt: {
            /**
             * Available Date
             * Format: date
             */
            available_date: string;
            /** Configuration Id */
            configuration_id: string;
            /**
             * Quantity
             * @description Incoming units on this date, not a balance
             */
            quantity: number;
        };
        /**
         * JobState
         * @enum {string}
         */
        JobState: "scheduled" | "locked" | "late" | "unscheduled" | "blocked";
        /**
         * Mode
         * @enum {string}
         */
        Mode: "strict" | "recovery";
        /**
         * MoveVisit
         * @description Intervention: put this visit on a chosen crew-day and keep it there.
         */
        MoveVisit: {
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Job Id */
            job_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "move_visit";
        };
        /** ObjectiveComponents */
        ObjectiveComponents: {
            /** Changed Installs */
            changed_installs: number;
            /** Crew Utilization */
            crew_utilization: number;
            /**
             * Customers To Reschedule
             * @description Distinct homes with at least one moved or dropped visit
             */
            customers_to_reschedule?: number | null;
            /** Jobs Blocked */
            jobs_blocked: number;
            /** Jobs Late */
            jobs_late: number;
            /** Jobs On Time */
            jobs_on_time: number;
            /**
             * Jobs Unscheduled
             * @description Includes blocked jobs
             */
            jobs_unscheduled: number;
            /**
             * Operating Value Usd
             * @description Value, USD
             */
            operating_value_usd: number;
            /**
             * Total Delay Days
             * @description Sum of days late over assigned jobs
             */
            total_delay_days: number;
            /**
             * Travel Allowance Min
             * @description Integer minutes
             */
            travel_allowance_min: number;
            /** Value Distinguishes Choices */
            value_distinguishes_choices: boolean;
            /**
             * Visits Moved
             * @description Planned visits moved or dropped. Same count as changed_installs
             */
            visits_moved?: number | null;
        };
        /**
         * ObjectivePolicy
         * @enum {string}
         */
        ObjectivePolicy: "value_aware" | "deadline_travel_only";
        /**
         * OptionKind
         * @enum {string}
         */
        OptionKind: "no_action" | "rebalance" | "overtime" | "temporary_capacity" | "custom";
        /**
         * Parameter
         * @description One operational number the model uses, with where it came from.
         */
        Parameter: {
            /**
             * Derivation
             * @description Rule, formula, or citation that produced the value
             */
            derivation: string;
            kind: components["schemas"]["DataKind"];
            /** Name */
            name: string;
            /**
             * Source
             * @description URL or reference, when one exists
             */
            source?: string | null;
            /** Unit */
            unit: string;
            /** Value */
            value: number | string;
        };
        /**
         * PinVisit
         * @description Intervention: keep this visit on its current crew-day.
         */
        PinVisit: {
            /** Job Id */
            job_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pin_visit";
        };
        /** PlanChange */
        PlanChange: {
            after: components["schemas"]["Slot"] | null;
            after_state: components["schemas"]["JobState"];
            before: components["schemas"]["Slot"] | null;
            before_state: components["schemas"]["JobState"];
            /** Job Id */
            job_id?: string | null;
            kind: components["schemas"]["ChangeKind"];
            /** Note */
            note: string;
            /** Site Id */
            site_id: string;
            visit_type?: components["schemas"]["VisitType"] | null;
        };
        /** PlanDiff */
        PlanDiff: {
            /** After Plan Id */
            after_plan_id: string;
            /** Before Plan Id */
            before_plan_id: string;
            /** Changes */
            changes: components["schemas"]["PlanChange"][];
            /** Headline */
            headline: string;
            summary: components["schemas"]["DiffSummary"];
        };
        /** PlanRequest */
        PlanRequest: {
            /** @default cpsat */
            algorithm: components["schemas"]["Algorithm"];
            /**
             * Edits
             * @default []
             */
            edits: (components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"] | components["schemas"]["ReduceCrewDay"] | components["schemas"]["ChangeAppointment"] | components["schemas"]["ExtendCrewDay"] | components["schemas"]["PinVisit"] | components["schemas"]["MoveVisit"])[];
            /** @default strict */
            mode: components["schemas"]["Mode"];
            objective_policy?: components["schemas"]["ObjectivePolicy"] | null;
            /**
             * Revision
             * @description Client edit counter, echoed in the result
             */
            revision: number;
            /** Scenario Id */
            scenario_id: string;
            /** Time Limit S */
            time_limit_s?: number | null;
        };
        /** PlanResult */
        PlanResult: {
            algorithm: components["schemas"]["Algorithm"];
            /** Assignments */
            assignments: components["schemas"]["Assignment"][];
            /** Assumptions */
            assumptions: components["schemas"]["Assumption"][];
            /** Crew Days */
            crew_days: components["schemas"]["CrewDayUsage"][];
            /** Edits */
            edits: (components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"] | components["schemas"]["ReduceCrewDay"] | components["schemas"]["ChangeAppointment"] | components["schemas"]["ExtendCrewDay"] | components["schemas"]["PinVisit"] | components["schemas"]["MoveVisit"])[];
            /**
             * Input Issues
             * @default []
             */
            input_issues: components["schemas"]["InputIssue"][];
            /**
             * Message
             * @description One or two plain sentences for the operator
             */
            message: string;
            mode: components["schemas"]["Mode"];
            objective: components["schemas"]["ObjectiveComponents"] | null;
            objective_policy: components["schemas"]["ObjectivePolicy"];
            /** Plan Id */
            plan_id: string;
            /** Revision */
            revision: number;
            /** Scenario Hash */
            scenario_hash: string;
            /** Scenario Id */
            scenario_id: string;
            /** Solve Ms */
            solve_ms: number;
            /** Stages */
            stages: components["schemas"]["StageMeta"][];
            status: components["schemas"]["PlanStatus"];
            /** Unscheduled */
            unscheduled: components["schemas"]["UnscheduledJob"][];
            validation: components["schemas"]["ValidationReport"];
        };
        /**
         * PlanStatus
         * @enum {string}
         */
        PlanStatus: "optimal" | "feasible" | "infeasible" | "timeout_no_incumbent" | "invalid_input";
        /**
         * PlannedInstall
         * @description One row of the current installation plan that a disruption may force to change.
         */
        PlannedInstall: {
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Job Id
             * @description Visit job; None for one-visit homes
             */
            job_id?: string | null;
            /** Locked */
            locked: boolean;
            /** Site Id */
            site_id: string;
        };
        /** ProvenanceNote */
        ProvenanceNote: {
            /**
             * Input
             * @description File or field this note covers, e.g. sites.csv:deadline
             */
            input: string;
            kind: components["schemas"]["DataKind"];
            /** Manifest Id */
            manifest_id?: string | null;
            /** Source */
            source: string;
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "NOT_READY" | "SKILL_MISMATCH" | "CLUSTER_NOT_ALLOWED" | "NO_LEGAL_DATE" | "NO_INVENTORY" | "CAPACITY" | "LOCK_CONFLICT" | "DEADLINE_BEFORE_READY";
        /** RecoveryCounts */
        RecoveryCounts: {
            /** Customers To Reschedule */
            customers_to_reschedule: number;
            /** Deadlines Missed */
            deadlines_missed: number;
            /**
             * Deadlines Recovered
             * @description Deadlines this option saves vs no action
             */
            deadlines_recovered: number;
            /**
             * Delay Days
             * @description Whole days
             */
            delay_days: number;
            /** Unscheduled */
            unscheduled: number;
            /** Visits Moved */
            visits_moved: number;
        };
        /** RecoveryEconomics */
        RecoveryEconomics: {
            /**
             * Advantage Vs No Action Usd
             * @description No-action net impact minus this one
             */
            advantage_vs_no_action_usd: number;
            /** Cost Per Deadline Recovered Usd */
            cost_per_deadline_recovered_usd?: number | null;
            /** Lines */
            lines: components["schemas"]["EconomicLine"][];
            /**
             * Net Impact Usd
             * @description Modeled cost of this option vs the original plan
             */
            net_impact_usd: number;
        };
        /** RecoveryOption */
        RecoveryOption: {
            /**
             * Action Label
             * @description A business action, e.g. "Crew IB +2h overtime"
             */
            action_label: string;
            counts: components["schemas"]["RecoveryCounts"];
            /** Crew Load */
            crew_load: components["schemas"]["CrewLoad"][];
            diff_vs_no_action: components["schemas"]["PlanDiff"] | null;
            diff_vs_original: components["schemas"]["PlanDiff"];
            economics: components["schemas"]["RecoveryEconomics"];
            /** Explanations */
            explanations: components["schemas"]["Explanation"][];
            /** Intervention Edits */
            intervention_edits: (components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"] | components["schemas"]["ReduceCrewDay"] | components["schemas"]["ChangeAppointment"] | components["schemas"]["ExtendCrewDay"] | components["schemas"]["PinVisit"] | components["schemas"]["MoveVisit"])[];
            kind: components["schemas"]["OptionKind"];
            /**
             * Lowest Modeled Cost
             * @default false
             */
            lowest_modeled_cost: boolean;
            /** Option Id */
            option_id: string;
            /**
             * Overtime Min
             * @description Integer minutes
             * @default 0
             */
            overtime_min: number;
            /** Proven Optimal */
            proven_optimal: boolean;
            result: components["schemas"]["PlanResult"];
            status: components["schemas"]["PlanStatus"];
            /**
             * Stub
             * @default false
             */
            stub: boolean;
        };
        /** RecoveryOptionsRequest */
        RecoveryOptionsRequest: {
            /**
             * Current Plan
             * @description None uses the scenario's current plan
             */
            current_plan?: components["schemas"]["PlannedInstall"][] | null;
            /** Disruption */
            disruption: (components["schemas"]["RemoveCrewDay"] | components["schemas"]["AddCrewDay"] | components["schemas"]["DelayInventory"] | components["schemas"]["ChangeReadyDate"] | components["schemas"]["ForceInclude"] | components["schemas"]["ReduceCrewDay"] | components["schemas"]["ChangeAppointment"] | components["schemas"]["ExtendCrewDay"] | components["schemas"]["PinVisit"] | components["schemas"]["MoveVisit"])[];
            /** Economics Overrides */
            economics_overrides?: {
                [key: string]: number;
            } | null;
            /**
             * Interactive
             * @default false
             */
            interactive: boolean;
            /** Revision */
            revision: number;
            /** Scenario Id */
            scenario_id: string;
        };
        /** RecoveryOptionsResult */
        RecoveryOptionsResult: {
            /** Assumptions */
            assumptions: components["schemas"]["Assumption"][];
            /** Economic Assumptions */
            economic_assumptions: components["schemas"]["EconomicAssumption"][];
            impact: components["schemas"]["ImpactAnalysis"];
            no_action: components["schemas"]["RecoveryOption"];
            /** Options */
            options: components["schemas"]["RecoveryOption"][];
            /** Revision */
            revision: number;
            /** Scenario Hash */
            scenario_hash: string;
            /**
             * Stub
             * @default false
             */
            stub: boolean;
        };
        /**
         * ReduceCrewDay
         * @description Disruption: reduced capacity. The crew-day keeps only available_min.
         */
        ReduceCrewDay: {
            /**
             * Available Min
             * @description Integer minutes
             */
            available_min: number;
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "reduce_crew_day";
        };
        /** RemoveCrewDay */
        RemoveCrewDay: {
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "remove_crew_day";
        };
        /** Scenario */
        Scenario: {
            /** Clusters */
            clusters: components["schemas"]["Cluster"][];
            config: components["schemas"]["ScenarioConfig"];
            /** Crew Days */
            crew_days: components["schemas"]["CrewDay"][];
            /** Current Plan */
            current_plan: components["schemas"]["PlannedInstall"][];
            /** Inventory */
            inventory: components["schemas"]["InventoryReceipt"][];
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Scenario Hash */
            scenario_hash: string;
            /** Scenario Id */
            scenario_id: string;
            /** Sites */
            sites: components["schemas"]["Site"][];
        };
        /** ScenarioConfig */
        ScenarioConfig: {
            /** Batteries */
            batteries: components["schemas"]["BatteryConfig"][];
            /** Description */
            description: string;
            /**
             * Evaluation End
             * Format: date
             */
            evaluation_end: string;
            /**
             * Min Gap Business Days
             * @description Business days from install to battery day. None means 1.
             */
            min_gap_business_days?: number | null;
            /** Name */
            name: string;
            /**
             * Num Workers
             * @default 8
             */
            num_workers: number;
            /** @default value_aware */
            objective_policy: components["schemas"]["ObjectivePolicy"];
            /**
             * Parameters
             * @default []
             */
            parameters: components["schemas"]["Parameter"][];
            /**
             * Planning End
             * Format: date
             */
            planning_end: string;
            /**
             * Planning Start
             * Format: date
             */
            planning_start: string;
            /** Provenance */
            provenance: components["schemas"]["ProvenanceNote"][];
            /**
             * Qualification Lag Days
             * @description Whole days
             * @default 0
             */
            qualification_lag_days: number;
            /**
             * Random Seed
             * @default 0
             */
            random_seed: number;
            /**
             * Solve Time Limit S
             * @default 15
             */
            solve_time_limit_s: number;
            /** Synthetic */
            synthetic: boolean;
            /**
             * Timezone
             * @default America/Chicago
             */
            timezone: string;
            /**
             * Unscheduled Penalty Days
             * @description Whole days
             */
            unscheduled_penalty_days: number;
            weather_rule?: components["schemas"]["WeatherRule"] | null;
        };
        /** ScenarioSummary */
        ScenarioSummary: {
            /** N Crew Days */
            n_crew_days: number;
            /** N Crews */
            n_crews: number;
            /** N Sites */
            n_sites: number;
            /** Name */
            name: string;
            /**
             * Planning End
             * Format: date
             */
            planning_end: string;
            /**
             * Planning Start
             * Format: date
             */
            planning_start: string;
            /** Scenario Hash */
            scenario_hash: string;
            /** Scenario Id */
            scenario_id: string;
            /** Synthetic */
            synthetic: boolean;
        };
        /** SeasonReplay */
        SeasonReplay: {
            /** Events */
            events: components["schemas"]["SeasonReplayEvent"][];
            /** Replay Id */
            replay_id: string;
            /** Stress Tests */
            stress_tests?: components["schemas"]["StressTest"][] | null;
            /**
             * Stub
             * @default false
             */
            stub: boolean;
            totals: components["schemas"]["SeasonTotals"];
        };
        /** SeasonReplayEvent */
        SeasonReplayEvent: {
            /** Case Id */
            case_id: string;
            chosen_option_kind: components["schemas"]["OptionKind"];
            no_action: components["schemas"]["RecoveryCounts"];
            /**
             * No Action Net Impact Usd
             * @description Value, USD
             */
            no_action_net_impact_usd: number;
            recovery: components["schemas"]["RecoveryCounts"];
            /**
             * Recovery Net Impact Usd
             * @description Value, USD
             */
            recovery_net_impact_usd: number;
            /** Solve Ms */
            solve_ms: number;
        };
        /** SeasonTotals */
        SeasonTotals: {
            /** Deadline Misses No Action */
            deadline_misses_no_action: number;
            /** Deadline Misses Recovery */
            deadline_misses_recovery: number;
            /** Deadlines Recovered */
            deadlines_recovered: number;
            /** Events Replayed */
            events_replayed: number;
            /** Median Solve Ms */
            median_solve_ms: number;
            /**
             * Modeled Cost No Action Usd
             * @description Value, USD
             */
            modeled_cost_no_action_usd: number;
            /**
             * Modeled Cost Recovery Usd
             * @description Value, USD
             */
            modeled_cost_recovery_usd: number;
        };
        /** Site */
        Site: {
            /** Cluster Id */
            cluster_id: string;
            /** Configuration Id */
            configuration_id: string;
            /**
             * Deadline
             * Format: date
             */
            deadline: string;
            /**
             * Duration Min
             * @description Integer minutes
             */
            duration_min: number;
            /** Lat */
            lat: number;
            /** Load Zone */
            load_zone: string;
            /** Lon */
            lon: number;
            /** Profile Id */
            profile_id?: string | null;
            /** Program Id */
            program_id: string;
            /**
             * Ready Date
             * Format: date
             */
            ready_date: string;
            /** Required Skill */
            required_skill: string;
            /** Site Id */
            site_id: string;
            /**
             * Visits
             * @description Empty: one visit described by duration_min and required_skill. Otherwise an install and a battery day; the deadline and energy value apply to the battery day, and duration_min / required_skill describe the battery day.
             * @default []
             */
            visits: components["schemas"]["Visit"][];
        };
        /** Slot */
        Slot: {
            /** Crew Id */
            crew_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
        };
        /** StageMeta */
        StageMeta: {
            /** Bound */
            bound?: number | null;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Gap */
            gap?: number | null;
            /** Name */
            name: string;
            status: components["schemas"]["StageStatus"];
            /** Value */
            value?: number | null;
        };
        /**
         * StageStatus
         * @enum {string}
         */
        StageStatus: "optimal" | "feasible" | "infeasible" | "timeout_no_incumbent" | "skipped";
        /** StormEvent */
        StormEvent: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Event Id */
            event_id: string;
            /** Max Wind Kmh */
            max_wind_kmh: number;
            /**
             * Rainfall Mm
             * @description Work hours, 08:00-17:00 local
             */
            rainfall_mm: number;
            /** Source */
            source: string;
            /**
             * Stub
             * @default false
             */
            stub: boolean;
            /** Thunder Hours */
            thunder_hours: number;
        };
        /** StressTest */
        StressTest: {
            /**
             * Advantage Usd
             * @description Value, USD
             */
            advantage_usd: number;
            /** Deadlines Recovered */
            deadlines_recovered: number;
            /** Variant */
            variant: string;
        };
        /** UnscheduledJob */
        UnscheduledJob: {
            /** Detail */
            detail: string;
            /**
             * Job Id
             * @description None covers the whole home
             */
            job_id?: string | null;
            /** Reasons */
            reasons: components["schemas"]["ReasonCode"][];
            /** Site Id */
            site_id: string;
            state: components["schemas"]["JobState"];
            visit_type?: components["schemas"]["VisitType"] | null;
        };
        /** ValidationIssue */
        ValidationIssue: {
            code: components["schemas"]["ViolationCode"];
            /** Crew Id */
            crew_id?: string | null;
            /** Date */
            date?: string | null;
            /** Job Id */
            job_id?: string | null;
            /** Message */
            message: string;
            /** Site Id */
            site_id?: string | null;
        };
        /** ValidationReport */
        ValidationReport: {
            /**
             * Checked
             * @description False until the independent validator ran
             */
            checked: boolean;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["ValidationIssue"][];
            /** Valid */
            valid: boolean;
            /** Validator */
            validator: string;
        };
        /**
         * ViolationCode
         * @enum {string}
         */
        ViolationCode: "UNKNOWN_SITE" | "DUPLICATE_ASSIGNMENT" | "NO_CREW_DAY" | "BEFORE_READY" | "AFTER_DEADLINE" | "MISSING_JOB" | "SKILL" | "CLUSTER_NOT_ALLOWED" | "MULTIPLE_CLUSTERS" | "CAPACITY" | "INVENTORY" | "LOCK_BROKEN" | "STATE_MISMATCH" | "OBJECTIVE_MISMATCH" | "PRECEDENCE";
        /**
         * Visit
         * @description One crew visit to a home. A two-visit home has an install, then a battery day.
         */
        Visit: {
            /**
             * Duration Min
             * @description Integer minutes
             */
            duration_min: number;
            /** Job Id */
            job_id: string;
            /** Required Skill */
            required_skill: string;
            visit_type: components["schemas"]["VisitType"];
        };
        /**
         * VisitType
         * @enum {string}
         */
        VisitType: "install" | "battery_day";
        /**
         * WeatherRule
         * @description A crew-day is lost when any working hour meets either condition.
         */
        WeatherRule: {
            /** Heavy Rain Mm Per H */
            heavy_rain_mm_per_h: number;
            /**
             * Thunder
             * @description Lose the day on any reported thunderstorm
             * @default true
             */
            thunder: boolean;
            /**
             * Work End Hour
             * @description Exclusive
             */
            work_end_hour: number;
            /** Work Start Hour */
            work_start_hour: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cases_api_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"][];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_plan_api_plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
            /** @description The request is valid JSON but makes no sense */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown scenario or path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request or the scenario files are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The planner produced a plan that failed validation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    compare_plans_api_plans_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDiff"];
                };
            };
            /** @description The request is valid JSON but makes no sense */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown scenario or path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request or the scenario files are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The planner produced a plan that failed validation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    run_counterfactual_api_plans_counterfactual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CounterfactualRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterfactualResult"];
                };
            };
            /** @description The request is valid JSON but makes no sense */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown scenario or path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request or the scenario files are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The planner produced a plan that failed validation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    recovery_approve_api_recovery_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResult"];
                };
            };
            /** @description The request is valid JSON but makes no sense */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown scenario or path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request or the scenario files are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The planner produced a plan that failed validation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    recovery_evaluate_api_recovery_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryOption"];
                };
            };
            /** @description The request is valid JSON but makes no sense */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown scenario or path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request or the scenario files are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The planner produced a plan that failed validation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    recovery_options_api_recovery_options_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryOptionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryOptionsResult"];
                };
            };
            /** @description The request is valid JSON but makes no sense */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown scenario or path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request or the scenario files are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The planner produced a plan that failed validation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioSummary"][];
                };
            };
        };
    };
    get_scenario_api_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"];
                };
            };
            /** @description The request is valid JSON but makes no sense */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unknown scenario or path */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The request or the scenario files are invalid */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The planner produced a plan that failed validation */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    season_replay_api_season_replay_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonReplay"];
                };
            };
        };
    };
    list_storms_api_storms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormEvent"][];
                };
            };
        };
    };
}
